FROM python:3.11-slim

RUN apt-get update && apt-get install -y \
    build-essential \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY dashboard/requirements_dash.txt ./dashboard/requirements_dash.txt

RUN pip install --no-cache-dir -r dashboard/requirements_dash.txt

EXPOSE 8501

CMD ["streamlit", "run", "dashboard/4_dashboard.py", "--server.port=8501", "--server.address=0.0.0.0"]